apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
 # finalizers:
 #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of application manifests
  source:
    repoURL: https://github.com/nrayyagari/kubernetes-microservices.git
    targetRevision: HEAD
    path: external-dns-manifest.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
