apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-applications
  namespace: argocd
 # finalizers:
 #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of application manifests
  source:
    repoURL: https://github.com/nrayyagari/kubernetes-microservices.git
    targetRevision: HEAD
    path: kubernetes-manifests/nginx-app-manifest.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
