apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-services
  namespace: argocd
spec:

  project: default
  # Source of application manifests
  source:
    repoURL: https://github.com/nrayyagari/kubernetes-microservices.git
    targetRevision: HEAD
    path: kubernetes-manifests/shared-services

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
