apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush         1
      Log_Level     info
      Daemon        off
      Parsers_File  parsers.conf
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE input-kubelet.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubelet.conf: |
    [INPUT]
      Name                systemd
      Tag                 systemd.*
      Path                /var/log/journal
      Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
      DB                  /var/log/flb_kubelet.db
      Read_From_Tail      true
      Parser              systemd-json
  input-kubernetes.conf: |
    [INPUT]
      Name               tail
      Tag                kube.*
      Path               /var/log/containers/*.log
      Parser             docker
      Docker_Mode        On
      Docker_Mode_Parser multi_line
      DB                 /var/log/flb_kube.db
      Mem_Buf_Limit      50MB
      Skip_Long_Lines    On
      Refresh_Interval   10
      Ignore_Older       24h
      Rotate_Wait        60
  filter-kubernetes.conf: |
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix     kube.var.log.containers.
      Merge_Log           On
      Merge_Log_Key       parsed
      K8S-Logging.Parser  On
      K8S-Logging.Exclude On
      Buffer_Size         1MB
    [FILTER]
      Name         nest
      Match        kube.*
      Wildcard     pod_name
      Operation    lift
      Nested_under kubernetes
      Add_prefix   kubernetes_
    [FILTER]
      Name   modify
      Match  kube.*
      Remove kubernetes_pod_id
      Remove kubernetes_container_hash
      Remove kubernetes_docker_id
    [FILTER]
      Name          nest
      Match         kube.*
      Wildcard      kubernetes_*
      Operation     nest
      Nest_under    kubernetes
      Remove_prefix kubernetes_
  output-elasticsearch.conf: |
    [OUTPUT]
      Name            es
      Match           *
      Host            ${FLUENT_ELASTICSEARCH_HOST}
      Port            ${FLUENT_ELASTICSEARCH_PORT}
      tls             On
      HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
      HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
      Logstash_Format On
      Logstash_Prefix logs
      Replace_Dots    On
      Retry_Limit     False
  parsers.conf: |
    [PARSER]
      Name   multi_line
      Format regex
      Regex  (?<log>^{"log":"[a-zA-Z0-9\[\{].*)
    [PARSER]
      Name         docker
      Format       json
      Time_Key     time
      Time_Format  %Y-%m-%dT%H:%M:%S.%L
      Time_Keep    On
    [PARSER]
      # https://rubular.com/r/IhIbCAIs7ImOkc
      Name        nginx-ingress
      Format      regex
      Regex       ^(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (\[(?<proxy_alternative_upstream_name>[^ ]*)\] )?(?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<reg_id>[^ ]*).*$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
      # https://rubular.com/r/xFYQq43QO3elLu
      Name        java
      Format      regex
      ## TODO when including the time filter fluent-bit breaks - need to investigate why
      #Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}\.\d{1,3})\s\|\s(?:.\[(?:\d;)?\d{1,2}m)?(?<level>\S*?)(?:.\[(?:\d;)?\d{1,2}m)?\s\|\s(?<thread>\S*)\s\|\s(?:.\[(?:\d;)?\d{1,2}m)?(?<class>\S*?)(?:.\[(?:\d;)?\d{1,2}m)?\s\|\s(?<message>.*)$
      Regex       ^(?:\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}\.\d{1,3})\s\|\s(?:.\[(?:\d;)?\d{1,2}m)?(?<level>\S*?)(?:.\[(?:\d;)?\d{1,2}m)?\s\|\s(?<thread>\S*)\s\|\s(?:.\[(?:\d;)?\d{1,2}m)?(?<class>\S*?)(?:.\[(?:\d;)?\d{1,2}m)?\s\|\s(?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%d %H:%M:%S.%L
    [PARSER]
      Name              systemd-json
      Format            json
      Decode_Field_As   escaped_utf8  MESSAGE  do_next

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: default
  labels:
    app.kubernetes.io/name: fluent-bit-logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit-logging
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit-logging
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.8.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 2020
          protocol: TCP
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "search-eks-nitin-1-nfiimso5yrxcfsdzxm2bj2egoi.us-east-1.es.amazonaws.com"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
        - name: FLUENT_ELASTICSEARCH_USER
          value: "admin"
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: "3O8QenRMn1A="
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - operator: Exists
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: default
  labels:
    app.kubernetes.io/name: fluent-bit-logging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit-logging