apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster-1
  region: us-east-1

vpc:
  id: vpc-05de13f328e16e7a5
  cidr: "10.0.0.0/16"
  subnets:
#    public:
#      us-east-1a:
#        id: subnet-0b54b65d2eb8356ad
#      us-east-1b:
#        id: subnet-06dd9e7af954f3d14
#      us-east-1c:
#        id: subnet-0d9a3c6ff4b7b3b1b
    private:
      us-east-1a:
        id: subnet-071f2e3d82da0deed
      us-east-1b:
        id: subnet-0ad5d5e79c546eec4
      us-east-1c:
        id: subnet-0aeab8a5afe25beda

nodeGroups:
  - name: EKS-private-workers
    instanceType: t2.small
    minSize: 2
    maxSize: 4
    ssh: 
      allow: true
      publicKeyName: kubekey
    tags:
      Name: ng-private
    privateNetworking: true