apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microservice1
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: microservice1.nitinayyagari.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: microservice1
                port:
                  number: 80
            path: / 
---
apiVersion: v1
kind: Service
metadata:
  name: microservice1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: microsevice1.nitinayyagari.com
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: microservice1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: nginx
        image: 927862243533.dkr.ecr.us-east-1.amazonaws.com/microservice1:b55fa6cf6b69e970db0c55f67bd4ed7d90636dc5-13
        ports:
          - containerPort: 80
