apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.nitinayyagari.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
            path: / 
---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: weather
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: 927862243533.dkr.ecr.us-east-1.amazonaws.com/microservice2:20a5ebf947851a29c91fdf4721215c9470eaad28-15
        ports:
          - containerPort: 3000