---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.nginx.com/stable
    targetRevision: 1.41.3
    chart: nginx-ingress

  destination:
    namespace: cs
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true