---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: cs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 15.1.0
    chart: prometheus
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: alertmanager.enabled
          value: 'false'
        - name: pushgateway.enabled
          value: 'false'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true



