apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster-1
  region: us-east-1

vpc:
  id: vpc-0592272fb1131f199
  cidr: "10.0.0.0/16"
  subnets:
#    public:
#      us-east-1a:
#        id: subnet-0b54b65d2eb8356ad
#      us-east-1b:
#        id: subnet-06dd9e7af954f3d14
#      us-east-1c:
#        id: subnet-0d9a3c6ff4b7b3b1b
    private:
      us-east-1a:
        id: subnet-0618e15e686962b9e
      us-east-1b:
        id: subnet-0b4027829a02b33a1
      us-east-1c:
        id: subnet-06e9bdff8feaed619

nodeGroups:
  - name: EKS-private-workers
    instanceType: t2.medium
    minSize: 3
    maxSize: 4
    ssh: 
      allow: true
      publicKeyName: kubekey
    tags:
      Name: ng-private
    privateNetworking: true