apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microservice1
  namespace: ms1
spec:
  ingressClassName: nginx
  rules:
    - host: microservice1.nitinayyagari.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: microservice1
                port:
                  number: 80
            path: / 
---
apiVersion: v1
kind: Service
metadata:
  name: microservice1
  namespace: ms1
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: microsevice1.nitinayyagari.com
  # removing annotation because hostname will be assigned to through ingress-microservice1
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: microservice1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: ms1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: nginx
        image: 927862243533.dkr.ecr.us-east-1.amazonaws.com/microservice1:8ccd8a8bb520be3ef76910e56e9320b0829f3059-11
        ports:
          - containerPort: 80
