apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: nginx.nitinayyagari.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
            path: / 
    - host: naaistam.nitinayyagari.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: naaistam
                port:
                  number: 80
            path: /