name: nginx-app-build-push-master

on:
  push:
    branches: [ main ]
    paths: 
      - 'microservices-src-dir/nginx-app/**'
env:
  AWS_REGION: us-east-1  # AWS Region where ECR is hosted one
  ECR_REPOSITORY: microservice1  # Push docker image to this ECR repository one
  APP_DIR: microservices-src-dir/nginx-app # Directory containing Dockerfile & app code
  # Kubernetes manifest file for the application. Github actions will update the image tag(most recent one) in this file after uploading to ECR
  MANIFEST_FILE_PATH: kubernetes-manifests/nginx-app-manifest.yaml 

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}
      run: |
        cd ${{ env.APP_DIR }}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Commit manifest file changes
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}
      run: |
        git pull --rebase
        sed -i "s#image:.*#image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG#g" ${{ env.MANIFEST_FILE_PATH }}
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ${{ env.MANIFEST_FILE_PATH }}
        git commit -m "Update image in ${{ env.MANIFEST_FILE_PATH }} for #${{ github.run_number }}"
      
    - name: Push manifest file changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}